[package]
name = "actix_hello"
version = "0.1.0"
authors = ["Kamek <b.kamek@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.18"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
